[package]
name = "moat-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
moat-core = { path = "../moat-core" }
csv = "1.1"
clap = { version = "4.0", features = ["derive", "env"] }
tokio = { version = "1.21", features = ["full"] }
dusk-bls12_381 = { version = "0.9", default-features = false, features = ["alloc", "pairings", "endo"] }
blake2 = { version = "0.10", default-features = false }
dusk-bytes = "0.1"
#dusk-wallet = "0.14"
#dusk-wallet = { git = "https://github.com/dusk-network/wallet-cli.git", branch = "rkyv" }
dusk-wallet = { path = "../../wallet-cli" }
wallet-accessor = { path = "../wallet-accessor" }

tracing = "0.1"
tracing-subscriber = "0.3"
