[package]
name = "moat-core"
version = "0.1.0"
edition = "2021"

[dependencies]
#csv = "1.1"
serde = { version = "1", features = ["derive"] }
tracing = "0.1"
serde_json = "1.0"
gql_client = "1.0"
thiserror = "1.0"
#anyhow = "1.0"
#chrono = { version = "0.4", features = ["serde"] }
#bs58 = "0.4"
toml-base-config = "0.1"
blake3 = "1.3"
#blake2 = { version = "0.10", default-features = false }
#dusk-wallet = "0.14"
#dusk-wallet = { git = "https://github.com/dusk-network/wallet-cli.git", branch = "rkyv" }
dusk-wallet = { path = "../../wallet-cli" }
rand = "0.8"
dusk-pki = "0.10.0-rc.1"
dusk-bytes = "0.1.6"
dusk-abi = "0.11"
rusk-abi = "0.8.0-alpha"
#dusk-bls12_381-sign = "0.3.0-rc"
dusk-bls12_381 = { version = "0.9", default-features = false, features = ["alloc", "pairings", "endo"] }
wallet-accessor = { path = "../wallet-accessor" }
rkyv = { version = "0.7", default-features = false }
bytecheck = "0.6"

[dev-dependencies]
tokio = { version = "1.15", features = ["rt-multi-thread", "time", "fs", "macros"] }
