[package]
name = "moat-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
toml-base-config = "0.1"
#dusk-wallet = "0.14"
#dusk-wallet = { git = "https://github.com/dusk-network/wallet-cli.git", branch = "rkyv" }
dusk-wallet = { path = "../../wallet-cli" }
rusk-abi = "0.8.0-alpha"
wallet-accessor = { path = "../wallet-accessor" }
rkyv = { version = "0.7", default-features = false }
bytecheck = "0.6"
gql_client = "1"
base64 = "0.21"
hex = "0.4"

[dev-dependencies]
tokio = { version = "1.15", features = ["rt-multi-thread", "time", "fs", "macros"] }
