[package]
name = "integration-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
moat-core={ path = "../moat-core" }
license-provider = { path = "../license-provider" }

[dev-dependencies]
dusk-wallet = { git = "https://github.com/dusk-network/wallet-cli.git", rev="1f994b1c" }
zk-citadel = { git = "https://github.com/dusk-network/citadel.git", rev="64844967" }
wallet-accessor = { path = "../wallet-accessor" }
rkyv = { version = "0.7", default-features = false }
tokio = { version = "1.15", features = ["rt-multi-thread", "time", "fs", "macros"] }
toml-base-config = "0.1"
gql_client = "1"
rand = "0.8"
bytecheck = "0.6"

[features]
int_tests = []
exp_tests = []
