[package]
name = "wallet-accessor"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
toml-base-config = "0.1"
blake3 = "1.3"
rkyv = { version = "0.7", default-features = false }
#dusk-wallet = "0.14"
dusk-wallet = { git = "https://github.com/dusk-network/wallet-cli.git", branch = "rkyv" }
dusk-wallet-core = "0.16.0-alpha"
dusk-abi = "0.11"
dusk-bls12_381 = "0.11"
rusk-abi = "0.8.0-alpha"
