[package]
name = "wallet-accessor"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1"
serde = { version = "1", features = ["derive"] }
toml-base-config = "0.1"
blake3 = "1.3"
rkyv = { version = "0.7", default-features = false }
#dusk-wallet = "0.14"
#dusk-wallet = { git = "https://github.com/dusk-network/wallet-cli.git", branch = "rkyv" }
dusk-wallet = { path = "../../wallet-cli" }
#dusk-wallet-core = "0.16.0-alpha"
dusk-wallet-core = "0.17.1-piecrust.0.5"
#dusk-wallet-core = { path = "../../wallet-core"}
dusk-abi = "0.11"
dusk-bls12_381 = "0.11"
rusk-abi = "0.8.0-piecrust.0.5"
phoenix-core = { version = "0.18", features = ["alloc"] }
