[package]
name = "wallet-accessor"
version = "0.1.0"
edition = "2021"

[dependencies]
dusk-wallet = { version = "0.16", git = "https://github.com/dusk-network/wallet-cli", tag = "0.16.0-rc.1" }
dusk-wallet-core = "0.19.0-piecrust.0.6"
phoenix-core = { version = "0.18", features = ["alloc"] }
dusk-bls12_381 = "0.11"
rusk-abi = { version = "0.9.0-piecrust.0.6", default-features = false }
rkyv = { version = "=0.7.39" }
tracing = "0.1"
serde = { version = "1", features = ["derive"] }
toml-base-config = "0.1"
blake3 = "1.3"
